### PR TITLE
Bring back file last modification time check

### LINKED ISSUE #303: Do we need to read the full file in order to detect already uploaded files?
Today I ran `gphotos-uploader-cli` on a subfolder of my photo library. As expected around 3GB of photos were uploaded to Google Photos. 

When running `gphotos-uploader-cli` for a second time, this took longer than expected. I store all my photos on a network share and although already uploaded files were skipped from being uploaded again, the network activity seemed to indicate that each file was being fully read from the network share.

I am new to this project, so I'm not sure what design decisions were made in the past, but I would assume that comparing the file modification time to a timestamp in the local database would be sufficient for determining if a file should be skipped or uploaded again. Many backup utilities work that way.

My use case may be exceptional as most people will probably run this program where the data lives, but even in that case, doing a simple stat call is going to be much faster and efficient than reading the file into memory.

### PR DESCRIPTION
**Pull request by mlangenberg**
My motivation for this PR can be read in #303. 

After merging these changes, we have brought back support for checking the last modification time of a file, before comparing file hashes. Hashing a file is a relatively expensive operation, especially when done over network.

I have searched through the repository's history and found that the program originally did store and check file modification times. I believe it still makes sense to do this. I could not find any documentation on why this was removed, so please excuse me when this proposal goes against any design decisions that were made in the past.

Personally I'm happy with the results of this change. On a network share with a source folder containing only 387 already uploaded photos (3GB in total) this improved the runtime from 72 seconds to 4 seconds.

I think we can improve the serialized form of the `TrackedFile` struct. For now I went for the original form `timestamp|hash` (timestamp as int, hash as string, delimited with '|').

Another thing that I would like feedback on is that the `Exists` function in `FileTracker` now possibly has the side effect of updating the `ModTime` field of the file marker. This is needed when the file last modified time changes, without changes to the file contents and when we don't have yet stored the last modified time on the marker (existing configurations).

It might be better to split that up to make the `Exists` function truly idempotent.

I will continue to do more tests with my own photo library, but this PR is ready for review.

**What issue type does this pull request address?** (keep at least one, remove the others)  
/kind enhancement

**What is this pull request for? Which issues does it resolve?** (use `resolves #<issue_number>` if possible)  
resolves #303 

**Does this pull request has user-facing changes?** (e.g. config changes, new/modified commands, new/modified flags)  
No

**Does this pull request add new dependencies?**  
No

### CODE REVIEW

File: internal/datastore/filetracker/filetracker.go [hunk 1]
```diff
@@ -16,6 +19,8 @@ type FileTracker struct {
 	// Hasher allows to change the way that hashes are calculated. Uses xxHash32Hasher{} by default.
 	// Useful for testing.
 	Hasher Hasher
+
+	logger log.Logger
```
Comment (pacoorozco) [inline internal/datastore/filetracker/filetracker.go:23]: This logger could be different from the `app.Logger`. With the current implementation it's going to be the same, but the logger may should be injected. 

This is not something you should address, but it's one of the problems I saw to use loggers inside some parts of the code :-D

File: internal/datastore/filetracker/filetracker.go [hunk 2]
```diff
@@ -37,16 +42,26 @@ func New(r Repository) *FileTracker {
 	return &FileTracker{
 		repo:   r,
 		Hasher: xxHash32Hasher{},
+		logger: log.GetInstance(),
```
Comment (pacoorozco) [inline internal/datastore/filetracker/filetracker.go:45]: This logger could be different from the app.Logger. With the current implementation it's going to be the same, but the logger may should be injected.

This is not something you should address, but it's one of the problems I saw to use loggers inside some parts of the code :-D

File: internal/datastore/filetracker/filetracker.go [hunk 3]
```diff
@@ -59,13 +74,32 @@ func (ft FileTracker) Exist(file string) bool {
...
 	}
 
 	// checks if the file is the same (equal value)
-	if item.Hash() == hash {
+	if item.Hash == hash {
+		ft.logger.Debugf("File hash has not changed for '%s'.", file)
+
+		// updates file marker with mtime to speed up comparison on next run
+		item.ModTime = fileInfo.ModTime()
+		if err = ft.repo.Put(file, item); err != nil {
```
Comment (pacoorozco) [inline internal/datastore/filetracker/filetracker.go:99]: I think that `Exist` is idempotent in the sense that it always returns the same output, no matter how many times you call it. But it's true that maybe is not obeying all the SOLID principles. 

For me it's not something to address now, but maybe readability could be improved extracting part to another method/function.

**Review by pacoorozco — APPROVED** [review]
Besides the comments, I think it could be merged....

**Comment by mlangenberg** [comment]
Thank you for your feedback and incorporating these changes so quickly! Hope it helps others as well.
